export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";
export const ADD_CATEGORY_RESET = "ADD_CATEGORY_RESET";

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
export const DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";
export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";

export const ADD_MENU_ITEMS_REQUEST = "ADD_MENU_ITEMS_REQUEST";
export const ADD_MENU_ITEMS_SUCCESS = "ADD_MENU_ITEMS_SUCCESS";
export const ADD_MENU_ITEMS_FAIL = "ADD_MENU_ITEMS_FAIL";
export const ADD_MENU_ITEMS_RESET = "ADD_MENU_ITEMS_RESET";

export const GET_MENU_ITEMS_REQUEST = "GET_MENU_ITEMS_REQUEST";
export const GET_MENU_ITEMS_SUCCESS = "GET_MENU_ITEMS_SUCCESS";
export const GET_MENU_ITEMS_FAIL = "GET_MENU_ITEMS_FAIL";

export const GET_MENU_ITEM_REQUEST = "GET_MENU_ITEM_REQUEST";
export const GET_MENU_ITEM_SUCCESS = "GET_MENU_ITEM_SUCCESS";
export const GET_MENU_ITEM_FAIL = "GET_MENU_ITEM_FAIL";

export const GET_MENU_SECTION_REQUEST = "GET_MENU_SECTION_REQUEST";
export const GET_MENU_SECTION_SUCCESS = "GET_MENU_SECTION_SUCCESS";
export const GET_MENU_SECTION_FAIL = "GET_MENU_SECTION_FAIL";

export const GET_OUTLET_ID_REQUEST = "GET_OUTLET_ID_REQUEST";
export const GET_OUTLET_ID_SUCCESS = "GET_OUTLET_ID_SUCCESS";
export const GET_OUTLET_ID_FAIL = "GET_OUTLET_ID_FAIL";

export const GET_OUTLETS_REQUEST  = 'GET_OUTLETS_REQUEST'
export const GET_OUTLETS_SUCCESS  = 'GET_OUTLETS_SUCCESS'
export const GET_OUTLETS_FAIL  = 'GET_OUTLETS_FAIL'

export const GET_MENUSECTIONS_REQUEST = 'GET_MENUSECTIONS_REQUEST'
export const GET_MENUSECTIONS_SUCCESS = 'GET_MENUSECTIONS_SUCCESS'
export const GET_MENUSECTIONS_FAIL = 'GET_MENUSECTIONS_FAIL'

export const GET_MSTYPE_REQUEST = 'GET_MSTYPE_REQUEST'
export const GET_MSTYPE_SUCCESS = 'GET_MSTYPE_SUCCESS'
export const GET_MSTYPE_FAIL = 'GET_MSTYPE_FAIL'

export const GET_MENU_BAR_REQUEST = "GET_MENU_BAR_REQUEST";
export const GET_MENU_BAR_SUCCESS = "GET_MENU_BAR_SUCCESS";
export const GET_MENU_BAR_FAIL = "GET_MENU_BAR_FAIL";